/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Attack_falloff.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Attack_falloff_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Attack_falloff_H_

#include "CppRestOpenAPIClient/ModelBase.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class Attack_falloff : public ModelBase {
public:
  Attack_falloff();
  virtual ~Attack_falloff();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// Attack_falloff members

  /// <summary>
  ///
  /// </summary>
  float getStart() const;
  bool startIsSet() const;
  void unsetStart();

  void setStart(float value);

  /// <summary>
  ///
  /// </summary>
  float getEnd() const;
  bool endIsSet() const;
  void unsetEnd();

  void setEnd(float value);

  /// <summary>
  ///
  /// </summary>
  float getReduction() const;
  bool reductionIsSet() const;
  void unsetReduction();

  void setReduction(float value);

protected:
  float m_Start;
  bool m_StartIsSet;
  float m_End;
  bool m_EndIsSet;
  float m_Reduction;
  bool m_ReductionIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Attack_falloff_H_ */
