/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Faction.h
 *
 * A Faction in Warframe
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Faction_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Faction_H_

#include "CppRestOpenAPIClient/ModelBase.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Faction : public ModelBase {
public:
  Faction();
  virtual ~Faction();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  enum class eFaction {
    Faction_OROKIN,
    Faction_CORRUPTED,
    Faction_INFESTED,
    Faction_CORPUS,
    Faction_GRINEER,
    Faction_TENNO,
    Faction_NARMER,
  };

  eFaction getValue() const;
  void setValue(eFaction const value);

protected:
  eFaction m_value;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Faction_H_ */
