/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetWorldstateByPlatform_400_response.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetWorldstateByPlatform_400_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetWorldstateByPlatform_400_response_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class GetWorldstateByPlatform_400_response : public ModelBase {
public:
  GetWorldstateByPlatform_400_response();
  virtual ~GetWorldstateByPlatform_400_response();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// GetWorldstateByPlatform_400_response members

  /// <summary>
  /// Description of error
  /// </summary>
  utility::string_t getError() const;
  bool errorIsSet() const;
  void unsetError();

  void setError(const utility::string_t &value);

  /// <summary>
  /// HTTP status code associated with error
  /// </summary>
  int32_t getCode() const;
  bool codeIsSet() const;
  void unsetCode();

  void setCode(int32_t value);

protected:
  utility::string_t m_Error;
  bool m_ErrorIsSet;
  int32_t m_Code;
  bool m_CodeIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetWorldstateByPlatform_400_response_H_ \
        */
