/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Language.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Language_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Language_H_

#include "CppRestOpenAPIClient/ModelBase.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Language : public ModelBase {
public:
  Language();
  virtual ~Language();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  utility::string_t toString() const;

  enum class eLanguage {
    Language_DE,
    Language_ES,
    Language_FR,
    Language_IT,
    Language_KO,
    Language_PL,
    Language_PT,
    Language_RU,
    Language_ZH,
    Language_EN,
    Language_UK,
  };

  eLanguage getValue() const;
  void setValue(eLanguage const value);

protected:
  eLanguage m_value;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Language_H_ */
