/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Patchlog.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Patchlog_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Patchlog_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class Patchlog : public ModelBase {
public:
  Patchlog();
  virtual ~Patchlog();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// Patchlog members

  /// <summary>
  ///
  /// </summary>
  utility::string_t getName() const;
  bool nameIsSet() const;
  void unsetName();

  void setName(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  utility::datetime getDate() const;
  bool dateIsSet() const;
  void unsetdate();

  void setDate(const utility::datetime &value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getUrl() const;
  bool urlIsSet() const;
  void unsetUrl();

  void setUrl(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getAdditions() const;
  bool additionsIsSet() const;
  void unsetAdditions();

  void setAdditions(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getChanges() const;
  bool changesIsSet() const;
  void unsetChanges();

  void setChanges(const utility::string_t &value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getFixes() const;
  bool fixesIsSet() const;
  void unsetFixes();

  void setFixes(const utility::string_t &value);

protected:
  utility::string_t m_Name;
  bool m_NameIsSet;
  utility::datetime m_date;
  bool m_dateIsSet;
  utility::string_t m_Url;
  bool m_UrlIsSet;
  utility::string_t m_Additions;
  bool m_AdditionsIsSet;
  utility::string_t m_Changes;
  bool m_ChangesIsSet;
  utility::string_t m_Fixes;
  bool m_FixesIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Patchlog_H_ */
