/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Riven.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Riven_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Riven_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Riven_rivenCompatability_value.h"
#include <map>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Riven_rivenCompatability_value;

/// <summary>
///
/// </summary>
class Riven : public ModelBase {
public:
  Riven();
  virtual ~Riven();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// Riven members

  /// <summary>
  /// The name of the weapon that this riven is compatible with
  /// </summary>
  std::map<utility::string_t, std::shared_ptr<Riven_rivenCompatability_value>> &
  getRivenCompatability();
  bool rivenCompatabilityIsSet() const;
  void unsetRivenCompatability();

  void setRivenCompatability(
      const std::map<utility::string_t,
                     std::shared_ptr<Riven_rivenCompatability_value>> &value);

protected:
  std::map<utility::string_t, std::shared_ptr<Riven_rivenCompatability_value>>
      m_RivenCompatability;
  bool m_RivenCompatabilityIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Riven_H_ */
