/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SlamAttack_radial.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SlamAttack_radial_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SlamAttack_radial_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Element.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class SlamAttack_radial : public ModelBase {
public:
  SlamAttack_radial();
  virtual ~SlamAttack_radial();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// SlamAttack_radial members

  /// <summary>
  ///
  /// </summary>
  float getDamage() const;
  bool damageIsSet() const;
  void unsetDamage();

  void setDamage(float value);

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<Element> getElement() const;
  bool elementIsSet() const;
  void unsetElement();

  void setElement(const std::shared_ptr<Element> &value);

  /// <summary>
  ///
  /// </summary>
  float getProc() const;
  bool procIsSet() const;
  void unsetProc();

  void setProc(float value);

  /// <summary>
  ///
  /// </summary>
  float getRadius() const;
  bool radiusIsSet() const;
  void unsetRadius();

  void setRadius(float value);

protected:
  float m_Damage;
  bool m_DamageIsSet;
  std::shared_ptr<Element> m_Element;
  bool m_ElementIsSet;
  float m_Proc;
  bool m_ProcIsSet;
  float m_Radius;
  bool m_RadiusIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SlamAttack_radial_H_ */
