/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppRestOpenAPIClient/model/CetusCycle.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CetusCycle::CetusCycle() {
  m_Id = utility::conversions::to_string_t("");
  m_IdIsSet = false;
  m_Activation = utility::datetime();
  m_ActivationIsSet = false;
  m_Expiry = utility::datetime();
  m_ExpiryIsSet = false;
  m_StartString = utility::conversions::to_string_t("");
  m_StartStringIsSet = false;
  m_Active = false;
  m_ActiveIsSet = false;
  m_IsDay = false;
  m_IsDayIsSet = false;
  m_State = utility::conversions::to_string_t("");
  m_StateIsSet = false;
  m_TimeLeft = utility::conversions::to_string_t("");
  m_TimeLeftIsSet = false;
  m_IsCetus = false;
  m_IsCetusIsSet = false;
  m_ShortString = utility::conversions::to_string_t("");
  m_ShortStringIsSet = false;
}

CetusCycle::~CetusCycle() {}

void CetusCycle::validate() {
  // TODO: implement validation
}

web::json::value CetusCycle::toJson() const {

  web::json::value val = web::json::value::object();

  if (m_IdIsSet) {
    val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
  }
  if (m_ActivationIsSet) {
    val[utility::conversions::to_string_t(U("activation"))] =
        ModelBase::toJson(m_Activation);
  }
  if (m_ExpiryIsSet) {
    val[utility::conversions::to_string_t(U("expiry"))] =
        ModelBase::toJson(m_Expiry);
  }
  if (m_StartStringIsSet) {
    val[utility::conversions::to_string_t(U("startString"))] =
        ModelBase::toJson(m_StartString);
  }
  if (m_ActiveIsSet) {
    val[utility::conversions::to_string_t(U("active"))] =
        ModelBase::toJson(m_Active);
  }
  if (m_IsDayIsSet) {
    val[utility::conversions::to_string_t(U("isDay"))] =
        ModelBase::toJson(m_IsDay);
  }
  if (m_StateIsSet) {
    val[utility::conversions::to_string_t(U("state"))] =
        ModelBase::toJson(m_State);
  }
  if (m_TimeLeftIsSet) {
    val[utility::conversions::to_string_t(U("timeLeft"))] =
        ModelBase::toJson(m_TimeLeft);
  }
  if (m_IsCetusIsSet) {
    val[utility::conversions::to_string_t(U("isCetus"))] =
        ModelBase::toJson(m_IsCetus);
  }
  if (m_ShortStringIsSet) {
    val[utility::conversions::to_string_t(U("shortString"))] =
        ModelBase::toJson(m_ShortString);
  }

  return val;
}

bool CetusCycle::fromJson(const web::json::value &val) {
  bool ok = true;

  if (val.has_field(utility::conversions::to_string_t(U("id")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("id")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setId;
      ok &= ModelBase::fromJson(fieldValue, refVal_setId);
      setId(refVal_setId);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("activation")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("activation")));
    if (!fieldValue.is_null()) {
      utility::datetime refVal_setActivation;
      ok &= ModelBase::fromJson(fieldValue, refVal_setActivation);
      setActivation(refVal_setActivation);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("expiry")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("expiry")));
    if (!fieldValue.is_null()) {
      utility::datetime refVal_setExpiry;
      ok &= ModelBase::fromJson(fieldValue, refVal_setExpiry);
      setExpiry(refVal_setExpiry);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("startString")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("startString")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setStartString;
      ok &= ModelBase::fromJson(fieldValue, refVal_setStartString);
      setStartString(refVal_setStartString);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("active")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("active")));
    if (!fieldValue.is_null()) {
      bool refVal_setActive;
      ok &= ModelBase::fromJson(fieldValue, refVal_setActive);
      setActive(refVal_setActive);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("isDay")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("isDay")));
    if (!fieldValue.is_null()) {
      bool refVal_setIsDay;
      ok &= ModelBase::fromJson(fieldValue, refVal_setIsDay);
      setIsDay(refVal_setIsDay);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("state")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("state")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setState;
      ok &= ModelBase::fromJson(fieldValue, refVal_setState);
      setState(refVal_setState);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("timeLeft")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("timeLeft")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setTimeLeft;
      ok &= ModelBase::fromJson(fieldValue, refVal_setTimeLeft);
      setTimeLeft(refVal_setTimeLeft);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("isCetus")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("isCetus")));
    if (!fieldValue.is_null()) {
      bool refVal_setIsCetus;
      ok &= ModelBase::fromJson(fieldValue, refVal_setIsCetus);
      setIsCetus(refVal_setIsCetus);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("shortString")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("shortString")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setShortString;
      ok &= ModelBase::fromJson(fieldValue, refVal_setShortString);
      setShortString(refVal_setShortString);
    }
  }
  return ok;
}

void CetusCycle::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }
  if (m_IdIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
  }
  if (m_ActivationIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("activation")),
        m_Activation));
  }
  if (m_ExpiryIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("expiry")), m_Expiry));
  }
  if (m_StartStringIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("startString")),
        m_StartString));
  }
  if (m_ActiveIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("active")), m_Active));
  }
  if (m_IsDayIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("isDay")), m_IsDay));
  }
  if (m_StateIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("state")), m_State));
  }
  if (m_TimeLeftIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("timeLeft")),
        m_TimeLeft));
  }
  if (m_IsCetusIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("isCetus")),
        m_IsCetus));
  }
  if (m_ShortStringIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("shortString")),
        m_ShortString));
  }
}

bool CetusCycle::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &prefix) {
  bool ok = true;
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }

  if (multipart->hasContent(utility::conversions::to_string_t(U("id")))) {
    utility::string_t refVal_setId;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("id"))),
        refVal_setId);
    setId(refVal_setId);
  }
  if (multipart->hasContent(
          utility::conversions::to_string_t(U("activation")))) {
    utility::datetime refVal_setActivation;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(
            utility::conversions::to_string_t(U("activation"))),
        refVal_setActivation);
    setActivation(refVal_setActivation);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("expiry")))) {
    utility::datetime refVal_setExpiry;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("expiry"))),
        refVal_setExpiry);
    setExpiry(refVal_setExpiry);
  }
  if (multipart->hasContent(
          utility::conversions::to_string_t(U("startString")))) {
    utility::string_t refVal_setStartString;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(
            utility::conversions::to_string_t(U("startString"))),
        refVal_setStartString);
    setStartString(refVal_setStartString);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("active")))) {
    bool refVal_setActive;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("active"))),
        refVal_setActive);
    setActive(refVal_setActive);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("isDay")))) {
    bool refVal_setIsDay;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("isDay"))),
        refVal_setIsDay);
    setIsDay(refVal_setIsDay);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("state")))) {
    utility::string_t refVal_setState;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("state"))),
        refVal_setState);
    setState(refVal_setState);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("timeLeft")))) {
    utility::string_t refVal_setTimeLeft;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("timeLeft"))),
        refVal_setTimeLeft);
    setTimeLeft(refVal_setTimeLeft);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("isCetus")))) {
    bool refVal_setIsCetus;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("isCetus"))),
        refVal_setIsCetus);
    setIsCetus(refVal_setIsCetus);
  }
  if (multipart->hasContent(
          utility::conversions::to_string_t(U("shortString")))) {
    utility::string_t refVal_setShortString;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(
            utility::conversions::to_string_t(U("shortString"))),
        refVal_setShortString);
    setShortString(refVal_setShortString);
  }
  return ok;
}

utility::string_t CetusCycle::getId() const { return m_Id; }

void CetusCycle::setId(const utility::string_t &value) {
  m_Id = value;
  m_IdIsSet = true;
}

bool CetusCycle::idIsSet() const { return m_IdIsSet; }

void CetusCycle::unsetId() { m_IdIsSet = false; }
utility::datetime CetusCycle::getActivation() const { return m_Activation; }

void CetusCycle::setActivation(const utility::datetime &value) {
  m_Activation = value;
  m_ActivationIsSet = true;
}

bool CetusCycle::activationIsSet() const { return m_ActivationIsSet; }

void CetusCycle::unsetActivation() { m_ActivationIsSet = false; }
utility::datetime CetusCycle::getExpiry() const { return m_Expiry; }

void CetusCycle::setExpiry(const utility::datetime &value) {
  m_Expiry = value;
  m_ExpiryIsSet = true;
}

bool CetusCycle::expiryIsSet() const { return m_ExpiryIsSet; }

void CetusCycle::unsetExpiry() { m_ExpiryIsSet = false; }
utility::string_t CetusCycle::getStartString() const { return m_StartString; }

void CetusCycle::setStartString(const utility::string_t &value) {
  m_StartString = value;
  m_StartStringIsSet = true;
}

bool CetusCycle::startStringIsSet() const { return m_StartStringIsSet; }

void CetusCycle::unsetStartString() { m_StartStringIsSet = false; }
bool CetusCycle::isActive() const { return m_Active; }

void CetusCycle::setActive(bool value) {
  m_Active = value;
  m_ActiveIsSet = true;
}

bool CetusCycle::activeIsSet() const { return m_ActiveIsSet; }

void CetusCycle::unsetActive() { m_ActiveIsSet = false; }
bool CetusCycle::isIsDay() const { return m_IsDay; }

void CetusCycle::setIsDay(bool value) {
  m_IsDay = value;
  m_IsDayIsSet = true;
}

bool CetusCycle::isDayIsSet() const { return m_IsDayIsSet; }

void CetusCycle::unsetIsDay() { m_IsDayIsSet = false; }
utility::string_t CetusCycle::getState() const { return m_State; }

void CetusCycle::setState(const utility::string_t &value) {
  m_State = value;
  m_StateIsSet = true;
}

bool CetusCycle::stateIsSet() const { return m_StateIsSet; }

void CetusCycle::unsetState() { m_StateIsSet = false; }
utility::string_t CetusCycle::getTimeLeft() const { return m_TimeLeft; }

void CetusCycle::setTimeLeft(const utility::string_t &value) {
  m_TimeLeft = value;
  m_TimeLeftIsSet = true;
}

bool CetusCycle::timeLeftIsSet() const { return m_TimeLeftIsSet; }

void CetusCycle::unsetTimeLeft() { m_TimeLeftIsSet = false; }
bool CetusCycle::isIsCetus() const { return m_IsCetus; }

void CetusCycle::setIsCetus(bool value) {
  m_IsCetus = value;
  m_IsCetusIsSet = true;
}

bool CetusCycle::isCetusIsSet() const { return m_IsCetusIsSet; }

void CetusCycle::unsetIsCetus() { m_IsCetusIsSet = false; }
utility::string_t CetusCycle::getShortString() const { return m_ShortString; }

void CetusCycle::setShortString(const utility::string_t &value) {
  m_ShortString = value;
  m_ShortStringIsSet = true;
}

bool CetusCycle::shortStringIsSet() const { return m_ShortStringIsSet; }

void CetusCycle::unsetShortString() { m_ShortStringIsSet = false; }
} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org
