/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppRestOpenAPIClient/model/GetWorldstateByPlatform_404_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GetWorldstateByPlatform_404_response::GetWorldstateByPlatform_404_response() {
  m_Error = utility::conversions::to_string_t("");
  m_ErrorIsSet = false;
  m_Code = 0;
  m_CodeIsSet = false;
}

GetWorldstateByPlatform_404_response::~GetWorldstateByPlatform_404_response() {}

void GetWorldstateByPlatform_404_response::validate() {
  // TODO: implement validation
}

web::json::value GetWorldstateByPlatform_404_response::toJson() const {

  web::json::value val = web::json::value::object();

  if (m_ErrorIsSet) {
    val[utility::conversions::to_string_t(U("error"))] =
        ModelBase::toJson(m_Error);
  }
  if (m_CodeIsSet) {
    val[utility::conversions::to_string_t(U("code"))] =
        ModelBase::toJson(m_Code);
  }

  return val;
}

bool GetWorldstateByPlatform_404_response::fromJson(
    const web::json::value &val) {
  bool ok = true;

  if (val.has_field(utility::conversions::to_string_t(U("error")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("error")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setError;
      ok &= ModelBase::fromJson(fieldValue, refVal_setError);
      setError(refVal_setError);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("code")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("code")));
    if (!fieldValue.is_null()) {
      int32_t refVal_setCode;
      ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
      setCode(refVal_setCode);
    }
  }
  return ok;
}

void GetWorldstateByPlatform_404_response::toMultipart(
    std::shared_ptr<MultipartFormData> multipart,
    const utility::string_t &prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }
  if (m_ErrorIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("error")), m_Error));
  }
  if (m_CodeIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("code")), m_Code));
  }
}

bool GetWorldstateByPlatform_404_response::fromMultiPart(
    std::shared_ptr<MultipartFormData> multipart,
    const utility::string_t &prefix) {
  bool ok = true;
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }

  if (multipart->hasContent(utility::conversions::to_string_t(U("error")))) {
    utility::string_t refVal_setError;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("error"))),
        refVal_setError);
    setError(refVal_setError);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("code")))) {
    int32_t refVal_setCode;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("code"))),
        refVal_setCode);
    setCode(refVal_setCode);
  }
  return ok;
}

utility::string_t GetWorldstateByPlatform_404_response::getError() const {
  return m_Error;
}

void GetWorldstateByPlatform_404_response::setError(
    const utility::string_t &value) {
  m_Error = value;
  m_ErrorIsSet = true;
}

bool GetWorldstateByPlatform_404_response::errorIsSet() const {
  return m_ErrorIsSet;
}

void GetWorldstateByPlatform_404_response::unsetError() {
  m_ErrorIsSet = false;
}
int32_t GetWorldstateByPlatform_404_response::getCode() const { return m_Code; }

void GetWorldstateByPlatform_404_response::setCode(int32_t value) {
  m_Code = value;
  m_CodeIsSet = true;
}

bool GetWorldstateByPlatform_404_response::codeIsSet() const {
  return m_CodeIsSet;
}

void GetWorldstateByPlatform_404_response::unsetCode() { m_CodeIsSet = false; }
} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org
