/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppRestOpenAPIClient/model/Introduced.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Introduced::Introduced() {
  m_Name = utility::conversions::to_string_t("");
  m_NameIsSet = false;
  m_Url = utility::conversions::to_string_t("");
  m_UrlIsSet = false;
  m_AliasesIsSet = false;
  m_Parent = utility::conversions::to_string_t("");
  m_ParentIsSet = false;
  m_dateIsSet = false;
}

Introduced::~Introduced() {}

void Introduced::validate() {
  // TODO: implement validation
}

web::json::value Introduced::toJson() const {

  web::json::value val = web::json::value::object();

  if (m_NameIsSet) {
    val[utility::conversions::to_string_t(U("name"))] =
        ModelBase::toJson(m_Name);
  }
  if (m_UrlIsSet) {
    val[utility::conversions::to_string_t(U("url"))] = ModelBase::toJson(m_Url);
  }
  if (m_AliasesIsSet) {
    val[utility::conversions::to_string_t(U("aliases"))] =
        ModelBase::toJson(m_Aliases);
  }
  if (m_ParentIsSet) {
    val[utility::conversions::to_string_t(U("parent"))] =
        ModelBase::toJson(m_Parent);
  }
  if (m_dateIsSet) {
    val[utility::conversions::to_string_t(U("date"))] =
        ModelBase::toJson(m_date);
  }

  return val;
}

bool Introduced::fromJson(const web::json::value &val) {
  bool ok = true;

  if (val.has_field(utility::conversions::to_string_t(U("name")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("name")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setName;
      ok &= ModelBase::fromJson(fieldValue, refVal_setName);
      setName(refVal_setName);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("url")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("url")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setUrl;
      ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
      setUrl(refVal_setUrl);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("aliases")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("aliases")));
    if (!fieldValue.is_null()) {
      std::vector<utility::string_t> refVal_setAliases;
      ok &= ModelBase::fromJson(fieldValue, refVal_setAliases);
      setAliases(refVal_setAliases);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("parent")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("parent")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setParent;
      ok &= ModelBase::fromJson(fieldValue, refVal_setParent);
      setParent(refVal_setParent);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("date")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("date")));
    if (!fieldValue.is_null()) {
      utility::datetime refVal_setDate;
      ok &= ModelBase::fromJson(fieldValue, refVal_setDate);
      setDate(refVal_setDate);
    }
  }
  return ok;
}

void Introduced::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }
  if (m_NameIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
  }
  if (m_UrlIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("url")), m_Url));
  }
  if (m_AliasesIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("aliases")),
        m_Aliases));
  }
  if (m_ParentIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("parent")), m_Parent));
  }
  if (m_dateIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("date")), m_date));
  }
}

bool Introduced::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &prefix) {
  bool ok = true;
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }

  if (multipart->hasContent(utility::conversions::to_string_t(U("name")))) {
    utility::string_t refVal_setName;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("name"))),
        refVal_setName);
    setName(refVal_setName);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("url")))) {
    utility::string_t refVal_setUrl;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("url"))),
        refVal_setUrl);
    setUrl(refVal_setUrl);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("aliases")))) {
    std::vector<utility::string_t> refVal_setAliases;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("aliases"))),
        refVal_setAliases);
    setAliases(refVal_setAliases);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("parent")))) {
    utility::string_t refVal_setParent;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("parent"))),
        refVal_setParent);
    setParent(refVal_setParent);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("date")))) {
    utility::datetime refVal_setDate;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("date"))),
        refVal_setDate);
    setDate(refVal_setDate);
  }
  return ok;
}

utility::string_t Introduced::getName() const { return m_Name; }

void Introduced::setName(const utility::string_t &value) {
  m_Name = value;
  m_NameIsSet = true;
}

bool Introduced::nameIsSet() const { return m_NameIsSet; }

void Introduced::unsetName() { m_NameIsSet = false; }
utility::string_t Introduced::getUrl() const { return m_Url; }

void Introduced::setUrl(const utility::string_t &value) {
  m_Url = value;
  m_UrlIsSet = true;
}

bool Introduced::urlIsSet() const { return m_UrlIsSet; }

void Introduced::unsetUrl() { m_UrlIsSet = false; }
std::vector<utility::string_t> &Introduced::getAliases() { return m_Aliases; }

void Introduced::setAliases(const std::vector<utility::string_t> &value) {
  m_Aliases = value;
  m_AliasesIsSet = true;
}

bool Introduced::aliasesIsSet() const { return m_AliasesIsSet; }

void Introduced::unsetAliases() { m_AliasesIsSet = false; }
utility::string_t Introduced::getParent() const { return m_Parent; }

void Introduced::setParent(const utility::string_t &value) {
  m_Parent = value;
  m_ParentIsSet = true;
}

bool Introduced::parentIsSet() const { return m_ParentIsSet; }

void Introduced::unsetParent() { m_ParentIsSet = false; }
utility::datetime Introduced::getDate() const { return m_date; }

void Introduced::setDate(const utility::datetime &value) {
  m_date = value;
  m_dateIsSet = true;
}

bool Introduced::dateIsSet() const { return m_dateIsSet; }

void Introduced::unsetdate() { m_dateIsSet = false; }
} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org
