/**
 * WarframeStat.us API
 * Simple API for data from the game Warframe. [Parser
 * Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items
 * Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts)
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppRestOpenAPIClient/model/SolNode_SolKey.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SolNode_SolKey::SolNode_SolKey() {
  m_Enemy = utility::conversions::to_string_t("");
  m_EnemyIsSet = false;
  m_Type = utility::conversions::to_string_t("");
  m_TypeIsSet = false;
  m_Value = utility::conversions::to_string_t("");
  m_ValueIsSet = false;
}

SolNode_SolKey::~SolNode_SolKey() {}

void SolNode_SolKey::validate() {
  // TODO: implement validation
}

web::json::value SolNode_SolKey::toJson() const {

  web::json::value val = web::json::value::object();

  if (m_EnemyIsSet) {
    val[utility::conversions::to_string_t(U("enemy"))] =
        ModelBase::toJson(m_Enemy);
  }
  if (m_TypeIsSet) {
    val[utility::conversions::to_string_t(U("type"))] =
        ModelBase::toJson(m_Type);
  }
  if (m_ValueIsSet) {
    val[utility::conversions::to_string_t(U("value"))] =
        ModelBase::toJson(m_Value);
  }

  return val;
}

bool SolNode_SolKey::fromJson(const web::json::value &val) {
  bool ok = true;

  if (val.has_field(utility::conversions::to_string_t(U("enemy")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("enemy")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setEnemy;
      ok &= ModelBase::fromJson(fieldValue, refVal_setEnemy);
      setEnemy(refVal_setEnemy);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("type")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("type")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setType;
      ok &= ModelBase::fromJson(fieldValue, refVal_setType);
      setType(refVal_setType);
    }
  }
  if (val.has_field(utility::conversions::to_string_t(U("value")))) {
    const web::json::value &fieldValue =
        val.at(utility::conversions::to_string_t(U("value")));
    if (!fieldValue.is_null()) {
      utility::string_t refVal_setValue;
      ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
      setValue(refVal_setValue);
    }
  }
  return ok;
}

void SolNode_SolKey::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                                 const utility::string_t &prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }
  if (m_EnemyIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("enemy")), m_Enemy));
  }
  if (m_TypeIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("type")), m_Type));
  }
  if (m_ValueIsSet) {
    multipart->add(ModelBase::toHttpContent(
        namePrefix + utility::conversions::to_string_t(U("value")), m_Value));
  }
}

bool SolNode_SolKey::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                                   const utility::string_t &prefix) {
  bool ok = true;
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(U("."))) {
    namePrefix += utility::conversions::to_string_t(U("."));
  }

  if (multipart->hasContent(utility::conversions::to_string_t(U("enemy")))) {
    utility::string_t refVal_setEnemy;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("enemy"))),
        refVal_setEnemy);
    setEnemy(refVal_setEnemy);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("type")))) {
    utility::string_t refVal_setType;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("type"))),
        refVal_setType);
    setType(refVal_setType);
  }
  if (multipart->hasContent(utility::conversions::to_string_t(U("value")))) {
    utility::string_t refVal_setValue;
    ok &= ModelBase::fromHttpContent(
        multipart->getContent(utility::conversions::to_string_t(U("value"))),
        refVal_setValue);
    setValue(refVal_setValue);
  }
  return ok;
}

utility::string_t SolNode_SolKey::getEnemy() const { return m_Enemy; }

void SolNode_SolKey::setEnemy(const utility::string_t &value) {
  m_Enemy = value;
  m_EnemyIsSet = true;
}

bool SolNode_SolKey::enemyIsSet() const { return m_EnemyIsSet; }

void SolNode_SolKey::unsetEnemy() { m_EnemyIsSet = false; }
utility::string_t SolNode_SolKey::getType() const { return m_Type; }

void SolNode_SolKey::setType(const utility::string_t &value) {
  m_Type = value;
  m_TypeIsSet = true;
}

bool SolNode_SolKey::typeIsSet() const { return m_TypeIsSet; }

void SolNode_SolKey::unsetType() { m_TypeIsSet = false; }
utility::string_t SolNode_SolKey::getValue() const { return m_Value; }

void SolNode_SolKey::setValue(const utility::string_t &value) {
  m_Value = value;
  m_ValueIsSet = true;
}

bool SolNode_SolKey::valueIsSet() const { return m_ValueIsSet; }

void SolNode_SolKey::unsetValue() { m_ValueIsSet = false; }
} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org
